<?php

namespace Database\Seeders;

use App\Models\Banco;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BancoSeeder extends Seeder
{
    public function run(): void
    {
        $bancos = [
            ['codigo' => '001', 'nome' => 'Banco do Brasil S.A.'],
            ['codigo' => '003', 'nome' => 'Banco da Amazônia S.A.'],
            ['codigo' => '004', 'nome' => 'Banco do Nordeste do Brasil S.A.'],
            ['codigo' => '007', 'nome' => 'Banco Nacional de Desenvolvimento Econômico e Social - BNDES'],
            ['codigo' => '012', 'nome' => 'Banco Inbursa S.A.'],
            ['codigo' => '021', 'nome' => 'BANESTES S.A. Banco do Estado do Espírito Santo'],
            ['codigo' => '024', 'nome' => 'Banco de Pernambuco S.A. - BANDEPE'],
            ['codigo' => '025', 'nome' => 'Banco Alfa S.A.'],
            ['codigo' => '029', 'nome' => 'Banco Itaú Consignado S.A.'],
            ['codigo' => '033', 'nome' => 'Banco Santander (Brasil) S.A.'],
            ['codigo' => '036', 'nome' => 'Banco Bradesco BBI S.A.'],
            ['codigo' => '037', 'nome' => 'Banco do Estado do Pará S.A.'],
            ['codigo' => '040', 'nome' => 'Banco Cargill S.A.'],
            ['codigo' => '041', 'nome' => 'Banco do Estado do Rio Grande do Sul S.A. (Banrisul)'],
            ['codigo' => '047', 'nome' => 'Banco do Estado de Sergipe S.A.'],
            ['codigo' => '062', 'nome' => 'Hipercard Banco Múltiplo S.A.'],
            ['codigo' => '063', 'nome' => 'Banco Bradescard S.A.'],
            ['codigo' => '065', 'nome' => 'Banco Andbank (Brasil) S.A.'],
            ['codigo' => '066', 'nome' => 'Banco Morgan Stanley S.A.'],
            ['codigo' => '069', 'nome' => 'Banco Crefisa S.A.'],
            ['codigo' => '070', 'nome' => 'BRB - Banco de Brasília S.A.'],
            ['codigo' => '074', 'nome' => 'Banco J. Safra S.A.'],
            ['codigo' => '075', 'nome' => 'Banco ABN Amro S.A.'],
            ['codigo' => '077', 'nome' => 'Banco Inter S.A.'],
            ['codigo' => '082', 'nome' => 'Banco Topázio S.A.'],
            ['codigo' => '083', 'nome' => 'Banco da China Brasil S.A.'],
            ['codigo' => '094', 'nome' => 'Banco Finaxis S.A.'],
            ['codigo' => '095', 'nome' => 'Banco Travelex S.A.'],
            ['codigo' => '096', 'nome' => 'Banco B3 S.A.'],
            ['codigo' => '102', 'nome' => 'Banco XP S.A.'],
            ['codigo' => '104', 'nome' => 'Caixa Econômica Federal'],
            ['codigo' => '107', 'nome' => 'Banco BOCOM BBM S.A.'],
            ['codigo' => '119', 'nome' => 'Banco Western Union do Brasil S.A.'],
            ['codigo' => '120', 'nome' => 'Banco Rodobens S.A.'],
            ['codigo' => '121', 'nome' => 'Banco Agibank S.A.'],
            ['codigo' => '125', 'nome' => 'Banco Genial S.A.'],
            ['codigo' => '128', 'nome' => 'Braza Bank S.A. Banco de Câmbio'],
            ['codigo' => '129', 'nome' => 'UBS Brasil Banco de Investimento S.A.'],
            ['codigo' => '144', 'nome' => 'Ebury Banco de Câmbio S.A.'],
            ['codigo' => '169', 'nome' => 'Banco Olé Bonsucesso Consignado S.A.'],
            ['codigo' => '184', 'nome' => 'Banco Itaú BBA S.A.'],
            ['codigo' => '204', 'nome' => 'Banco Bradesco Cartões S.A.'],
            ['codigo' => '208', 'nome' => 'Banco BTG Pactual S.A.'],
            ['codigo' => '212', 'nome' => 'Banco Original S.A.'],
            ['codigo' => '217', 'nome' => 'Banco John Deere S.A.'],
            ['codigo' => '218', 'nome' => 'Banco BS2 S.A.'],
            ['codigo' => '222', 'nome' => 'Banco Credit Agricole Brasil S.A.'],
            ['codigo' => '224', 'nome' => 'Banco Fibra S.A.'],
            ['codigo' => '233', 'nome' => 'Banco Cifra S.A.'],
            ['codigo' => '237', 'nome' => 'Banco Bradesco S.A.'],
            ['codigo' => '243', 'nome' => 'Banco Master S.A.'],
            ['codigo' => '246', 'nome' => 'Banco ABC Brasil S.A.'],
            ['codigo' => '249', 'nome' => 'Banco Investcred Unibanco S.A.'],
            ['codigo' => '250', 'nome' => 'BCV - Banco de Crédito e Varejo S.A.'],
            ['codigo' => '254', 'nome' => 'Paraná Banco S.A.'],
            ['codigo' => '260', 'nome' => 'Nu Pagamentos S.A. (Nubank)'],
            ['codigo' => '265', 'nome' => 'Banco Fator S.A.'],
            ['codigo' => '269', 'nome' => 'Banco HSBC S.A.'],
            ['codigo' => '290', 'nome' => 'Pagseguro Internet S.A.'],
            ['codigo' => '299', 'nome' => 'Banco Afinz S.A. Banco Múltiplo'],
            ['codigo' => '318', 'nome' => 'Banco BMG S.A.'],
            ['codigo' => '320', 'nome' => 'Bank Of China (Brasil) Banco Múltiplo S.A.'],
            ['codigo' => '336', 'nome' => 'Banco C6 S.A.'],
            ['codigo' => '341', 'nome' => 'Itaú Unibanco S.A.'],
            ['codigo' => '348', 'nome' => 'Banco XP S.A.'],
            ['codigo' => '366', 'nome' => 'Banco Société Générale Brasil S.A.'],
            ['codigo' => '370', 'nome' => 'Banco Mizuho do Brasil S.A.'],
            ['codigo' => '376', 'nome' => 'Banco J. P. Morgan S.A.'],
            ['codigo' => '386', 'nome' => 'Nu Financeira S.A.'],
            ['codigo' => '389', 'nome' => 'Banco Mercantil do Brasil S.A.'],
            ['codigo' => '394', 'nome' => 'Banco Bradesco Financiamentos S.A.'],
            ['codigo' => '399', 'nome' => 'Kirton Bank S.A. - Banco Múltiplo'],
            ['codigo' => '412', 'nome' => 'Banco Capital S.A.'],
            ['codigo' => '422', 'nome' => 'Banco Safra S.A.'],
            ['codigo' => '456', 'nome' => 'Banco MUFG Brasil S.A.'],
            ['codigo' => '464', 'nome' => 'Banco Sumitomo Mitsui Brasileiro S.A.'],
            ['codigo' => '473', 'nome' => 'Banco Caixa Geral - Brasil S.A.'],
            ['codigo' => '477', 'nome' => 'Citibank N.A.'],
            ['codigo' => '479', 'nome' => 'Banco ItauBank S.A'],
            ['codigo' => '487', 'nome' => 'Deutsche Bank S.A. - Banco Alemão'],
            ['codigo' => '488', 'nome' => 'JPMorgan Chase Bank, National Association'],
            ['codigo' => '496', 'nome' => 'BBVA Brasil Banco de Investimento S.A.'],
            ['codigo' => '505', 'nome' => 'Banco Credit Suisse (Brasil) S.A.'],
            ['codigo' => '600', 'nome' => 'Banco Luso Brasileiro S.A.'],
            ['codigo' => '604', 'nome' => 'Banco Industrial do Brasil S.A.'],
            ['codigo' => '610', 'nome' => 'Banco VR S.A.'],
            ['codigo' => '611', 'nome' => 'Banco Paulista S.A.'],
            ['codigo' => '612', 'nome' => 'Banco Guanabara S.A.'],
            ['codigo' => '613', 'nome' => 'Omni Banco S.A.'],
            ['codigo' => '623', 'nome' => 'Banco Pan S.A.'],
            ['codigo' => '626', 'nome' => 'Banco Ficsa S.A.'],
            ['codigo' => '630', 'nome' => 'Banco Smartbank S.A.'],
            ['codigo' => '633', 'nome' => 'Banco Rendimento S.A.'],
            ['codigo' => '634', 'nome' => 'Banco Triângulo S.A.'],
            ['codigo' => '641', 'nome' => 'Banco Alvorada S.A.'],
            ['codigo' => '643', 'nome' => 'Banco Pine S.A.'],
            ['codigo' => '653', 'nome' => 'Banco Indusval S.A.'],
            ['codigo' => '654', 'nome' => 'Banco Digimais S.A.'],
            ['codigo' => '655', 'nome' => 'Banco Votorantim S.A.'],
            ['codigo' => '707', 'nome' => 'Banco Daycoval S.A.'],
            ['codigo' => '712', 'nome' => 'Banco Ourinvest S.A.'],
            ['codigo' => '745', 'nome' => 'Banco Citibank S.A.'],
            ['codigo' => '746', 'nome' => 'Banco Modal S.A.'],
            ['codigo' => '747', 'nome' => 'Banco Rabobank International Brasil S.A.'],
            ['codigo' => '748', 'nome' => 'Sicredi (Sistema de Crédito Cooperativo)'],
            ['codigo' => '751', 'nome' => 'Scotiabank Brasil S.A. Banco Múltiplo'],
            ['codigo' => '752', 'nome' => 'Banco BNP Paribas Brasil S.A.'],
            ['codigo' => '755', 'nome' => 'Bank of America Merrill Lynch Banco Múltiplo S.A.'],
            ['codigo' => '756', 'nome' => 'Sicoob (Sistema de Cooperativas de Crédito do Brasil)'],
        ];

        foreach($bancos as $banco) {
            Banco::query()->create($banco);
        }
    }
}
